config {
    type: "view",
    name: "order_items_intermediate",
    schema: dataform.projectConfig.vars.orders_intermediate_dataset,
    description: "Order Items Intermediate",
    tags: ["intermediate"],

    bigquery: {
        labels: {
            data_domain: "orders",
            data_level: variables.intermediate_data_level,
        }
    },

    assertions: {
        nonNull: ["order_id"]
    }
}

SELECT
*
FROM ${ref("order_items_source")}
